spring.application.name=autenticacion
# Configuración MySQL
spring.datasource.url=jdbc:oracle:thin:@practica2025_high?TNS_ADMIN=C:/Wallet
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
spring.datasource.username=USERS_TIENDA
spring.datasource.password=Oracle12345%
server.port=8081

# JPA
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.OracleDialect
# Agrupar inserts en bloques de 50 para no saturar la red hacia la nube
spring.jpa.properties.hibernate.jdbc.batch_size=50
spring.jpa.properties.hibernate.order_inserts=true

# JWT Configuration
jwt.refresh-expiration=604800000
jwt.secret=${JWT_SECRET}
jwt.expiration=3600000
